# Generated by Django 4.2.7 on 2023-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0002_alter_newsarticle_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='intensity',
            field=models.CharField(max_length=10),
        ),
    ]
