# Generated by Django 4.2.7 on 2023-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_alter_newsarticle_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='likelihood',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='relevance',
            field=models.CharField(max_length=10),
        ),
    ]
